---
name: String-Fraction
version: 0.20
author:
  - Copyright Mark Fowler <mark@twoshortplanks.com> and Fotango 2005.
abstract: convert fractions into unicode chars
license: perl
requires:
  HTML::Fraction: 0.40
build_requires:
  Test::More: 0
provides:
  String::Fraction:
    file: lib/String/Fraction.pm
    version: 0.20
generated_by: Module::Build version 0.261
