---
abstract: 'convert fractions into unicode chars'
author:
  - 'Copyright Mark Fowler <mark@twoshortplanks.com> and Fotango 2005.'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-Fraction
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  HTML::Fraction: 0.4
resources:
  homepage: http://github.com/2shortplanks/String-Fraction/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/2shortplanks/String-Fraction.git
version: 0.30
